name: Context Auto-Generation

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '.claude/context/**'

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  generate-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Read skill files
        id: read-skills
        run: |
          {
            echo "agent_def<<AGENT_EOF"
            cat .claude/agents/context-generator.md
            echo "AGENT_EOF"
          } >> $GITHUB_OUTPUT
          {
            echo "skill_guide<<SKILL_EOF"
            cat .claude/skills/ContextGeneration/SKILL.md
            echo "SKILL_EOF"
          } >> $GITHUB_OUTPUT

      - name: Generate context documents
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          show_full_output: true
          claude_args: '--model opus --allowedTools "Bash(git:*),Bash(ls:*),Bash(mkdir:*),Read,Write,Edit,Glob,Grep"'
          prompt: |
            # 에이전트 정의
            ${{ steps.read-skills.outputs.agent_def }}

            # 스킬 가이드
            ${{ steps.read-skills.outputs.skill_guide }}

            # 작업 지시
            PR diff를 분석하고 .claude/context/ 아래에 컨텍스트 문서를 생성/업데이트하세요.

            단계:
            1. `git diff HEAD~1 --name-only`을 실행하여 변경된 파일 목록 가져오기
            2. 변경된 각 모듈에 대해 .claude/context/codebase/<module>.md 생성 또는 업데이트
            3. 영향을 받는 각 비즈니스 도메인에 대해 .claude/context/business/<domain>.md 생성 또는 업데이트
            4. 두 디렉토리의 INDEX.md 파일 업데이트

            중요사항:
            - 컨텍스트 문서에 소스 코드를 포함하지 말고, 파일 경로와 함수 이름만 포함하세요
            - 실제로 변경된 파일에 대해서만 컨텍스트 업데이트
            - 위 스킬 가이드에 명시된 정확한 형식 따르기
            - 커밋하지 마세요. 파일 생성/수정만 하세요.

      - name: Push context to separate branch and create PR
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"

          git add .claude/context/
          if git diff --staged --quiet; then
            echo "No context changes detected"
            exit 0
          fi

          CONTEXT_BRANCH="${{ github.head_ref }}-generated-context"
          git commit -m "docs: context 문서 자동 업데이트"
          git push --force origin HEAD:refs/heads/${CONTEXT_BRANCH}

          # 기존 PR이 있으면 스킵, 없으면 생성
          EXISTING_PR=$(gh pr list --head "${CONTEXT_BRANCH}" --base "${{ github.head_ref }}" --json number --jq '.[0].number')
          if [ -z "$EXISTING_PR" ]; then
            gh pr create \
              --head "${CONTEXT_BRANCH}" \
              --base "${{ github.head_ref }}" \
              --title "docs: context 문서 자동 업데이트" \
              --body "$(cat <<'PREOF'
          ## Auto-generated Context

          PR의 코드 변경을 분석하여 자동 생성된 context 문서입니다.
          선택적으로 머지하여 반영할 수 있습니다.

          > 이 PR은 re-sync 시 force push로 업데이트됩니다.
          PREOF
          )"
          else
            echo "PR #${EXISTING_PR} already exists, force-pushed updates"
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}
