name: Context Auto-Generation

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '.claude/context/**'

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  generate-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Generate context documents
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          show_full_output: true
          claude_args: '--allowedTools "Bash(git:*),Bash(ls:*),Bash(mkdir:*),Read,Write,Edit,Glob,Grep"'
          prompt: |
            당신은 context-generator 에이전트입니다.
            .claude/agents/context-generator.md의 에이전트 정의와
            .claude/skills/ContextGeneration/SKILL.md의 스킬 가이드를 읽고 정확히 따르세요.

            PR diff를 분석하고 .claude/context/ 아래에 컨텍스트 문서를 생성/업데이트하세요.

            단계:
            1. `git diff HEAD~1 --name-only`을 실행하여 변경된 파일 목록 가져오기
            2. 변경된 각 모듈에 대해 .claude/context/codebase/<module>.md 생성 또는 업데이트
            3. 영향을 받는 각 비즈니스 도메인에 대해 .claude/context/business/<domain>.md 생성 또는 업데이트
            4. 두 디렉토리의 INDEX.md 파일 업데이트
            5. "docs: update context for PR changes" 메시지로 변경사항 커밋

            중요사항:
            - 컨텍스트 문서에 소스 코드를 포함하지 말고, 파일 경로와 함수 이름만 포함하세요
            - 실제로 변경된 파일에 대해서만 컨텍스트 업데이트
            - ContextGeneration 스킬에 명시된 정확한 형식 따르기

      - name: Push context changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .claude/context/
          git diff --staged --quiet || git commit -m "docs: context 문서 자동 업데이트"
          git push || echo "Nothing to push"
